version: '3.8'

services:
   web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn app_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - code/.env.prod
    depends_on:
      - db    
      - redis
    restart: always
   db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - code/.env.prod.db
   redis:
      image: redis:alpine
      restart: always
volumes:
   postgres_data:
