version: '3.8'

services:
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - code/.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=memes
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=memes_dev
  redis:
    image: redis:alpine
volumes:
  postgres_data:
