version: '3.8'
services:
  web:
    build: .
    dockerfile: Dockerfile.prod
    command: gunicorn app_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    restart: always
  volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db 
  redis:
    image: redis:alpine
volumes:
  postgres_data:
